FROM dockette/web:php-80

RUN sed -i "s/display_errors = Off/display_errors = On/" /etc/php/8.0/fpm/php.ini
RUN sed -i "s/display_startup_errors = Off/display_startup_errors = On/" /etc/php/8.0/fpm/php.ini
