version: '3.3'

services:
    web:
        image: nettrine_web
        build: .docker
        volumes:
            - ./:/var/www/html
            - ./.docker/apache/sites-enabled:/etc/apache2/sites-enabled
        ports:
            - 8080:80

        links:
            - database

    database:
        image: mariadb:latest
        environment:
            MYSQL_ROOT_PASSWORD: root
            MYSQL_USER: nettrine
            MYSQL_PASSWORD: password
            MYSQL_DATABASE: nettrine

    adminer:
        image: adminer:latest
        ports:
            - 8081:8080

    composer:
        image: composer:latest
        volumes:
            - ./:/app
        working_dir: /app
        command: >
            bash -c "docker-php-ext-install mysqli &&
                    docker-php-ext-enable mysqli &&
                    composer install --ignore-platform-reqs &&
                    php bin/console migrations:migrate -n &&
                    php bin/console doctrine:fixtures:load -n"

    console:
        image: nettrine_web
        entrypoint: bin/console
        volumes:
            - ./:/var/www/html
