name: contributte/pdf tests

on:
  pull_request:
    paths-ignore:
      - ".docs/**"
  push:
    branches:
      - "*"
  schedule:
    - cron: "0 8 * * 1" # At 08:00 on Monday

jobs:
  tests:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        php: ['7.4']

      fail-fast: false

    name: PHP ${{ matrix.php }} contributte/pdf tests
    steps:
      - uses: actions/checkout@v2
      - uses: shivammathur/setup-php@v1
        with:
          php-version: ${{ matrix.php }}
          extensions: gd, json, mbstring, tokenizer
          coverage: none

      - run: cd contributte-pdf && make
      - run: cd contributte-pdf && make qa
